version: "3"

services:
    db:
        image: mysql:8
        restart: always
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        env_file:
            - docker.env
        volumes:
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

    redis:
        image: redis:7
        restart: always
        env_file:
            - docker.env
        command: redis-server  --requirepass ${REDIS_PASSWORD}

    app:
        image: alisonmjc/senao_app:0.2.0
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - 8000:8000
        depends_on:
            - db
        environment:
            - DB_HOST=db
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - REDIS_HOST=redis
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        env_file:
            - docker.env
